#所有水文模型在hydro目录下
#/------------------------------------------------------------------/
#/                           数据预处理
#/------------------------------------------------------------------/

flow_file_paths: './data/1.csv'  #实际流量数据
path_out: './data/post_proce.csv'  #处理后流量数据
rain_file_paths: './hydro/input_raindata.csv'   #降雨数据位置

#/------------------------------------------------------------------/
#/                           洪水分割聚类
#/------------------------------------------------------------------/
theta: 24 #默认
n_clusters: 1  #聚类个数
 

#/------------------------------------------------------------------/
#/                           优化算法
#/------------------------------------------------------------------/

cas_path : './hydro/settings_calc.cas'  #cas文件位置
pre_path : './hydro/results'  #预测结果目录
para_path : './hydro/params/param_xaj'  #参数目录

ini_candidate: 'Y'  #是否使用初始解 Y为是


mode : 'A' # 模式A，15个新安江参数。模式B：15个新安江参数 + 2个mskg参数


column_num: [1, 2]  #率定的流域第几列

core: 8  #核数

mskg_columns: [1] #mskg的预测数据的行，B模式才会读取

precision: 0.0001  #参数精度

n_gen: 20 #迭代次数

pop_size: 4 #种群大小
